language: python
sudo: false
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36,codecov
install:
- pip install -U pip tox
script:
- tox
deploy:
  provider: pypi
  user: cfhamlet
  script: pip install --upgrade setuptools wheel
  password:
    secure: GiKJvTwTWi/7YM6Xu2y64r81xTaQht6K1dt7dA2a6azRtr/B08Ihq0byat51PsUUqf3iOuxECjGvVDxHfzHYoLqDo2k5xVBI2FEzjauv1dMcDD/HMFjSvHQjIJjnKpT2sDMk7FEIwYm/+rAcDRsQMkNTSzlVNL+WEFYOQVSQPy9kzs/Pcqm8r12QM8i6MSMbAQMlat2VBhyh6Y9MF36RHmNNilMpdshPsvrMfXnWzEomBwr2xeYIp0eWTiyCd5aJrD8e9K58IFuBdrEdmR/K5XX0cFKVePxFIhNPeIwJAE3Fo4X5YZTlTd1WXAWJlYkkkKgCDXA4NnrhZuEnTeqEFc7lb7LwWvzOPLO9Z5cgXBkh3L8qKKXIiy3bOwZeuHGkCRCXFkuv57lR1KoXj3N1XNI1mDYitqsX2vI00TZe1sU3tTi1PbHTTQ6GtQdd2gEGJMQd8oKqUBA1vnrTJcQ8aBicsuh+bW223c2MKGpn6at54KaN4aaDn217Wm31lzuX3R6hPul1s6Wo2gzebXC0DKEqhwxGiIEOJTV/JnKM/gE9nq1CuBU9LDed/96GoSBsDnM3sOPXtI12e2qDKD72Z1tgyJUpFmJwFzjMPhYlIkk4KdUWKaM0rP+e68Io/lZCxKdwSQjSqAfoWeL9Db5z7OVcrWTxUikKdmqBkk9gcfk=
  true:
    tags: true
    condition: ${TRAVIS_PYTHON_VERSION} == 3.6
