language: python
sudo: false
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36,codecov
install:
- pip install -U pip tox
script:
- tox
deploy:
  provider: pypi
  user: cfhamlet
  script: pip install --upgrade setuptools wheel
  password:
    secure: Iw9wsoTR0RoXMzU+aO0JN8bCdi9N7TjvbSetGrQrpP/dYFTupg0a4Zp2xazze0Qpi6oBdjegcCIjkZL6Gio/5dZcyYKK2A8hNI3iyuCaa3Hea/XJ4mY/wXeMeQTeiQxzCS556FaZ9AiUMwI5wAcXhu154XJf7nyPvWtBIjUXmK1zwJxB+p/FWPVOCnXQbO40uh9yHuZ/YBo6pvgjMJNo3WR1oBEGM+t/ACINU+E9pNHS9fpmyQ+n9S/QZOJwjV9sbJMepeE7lwrvUioNtPDqetO6E50Bq0brBmZFf1tyrVlSoCZD0GuKS6vNLgC5jNJEciTuDoKpUc/81qT94yqnC9pll9hSByD4Y7WbBbQbjpq+rnjKKtJK53ewaXdUJWZ2Xa5FUZuJaVayowMUXkml3zE5IXMZnPrS4skmAZ3oAGdBJNZmFEWOx06NqsqsG/eKduEdkroLrZw2sImOvuY+WP1IZSjEjq0nubasvvuYLSRKJ/VcmA1sJpBVULxhF0eh72qldJ2R+twrgrBFWQRhXxaFDqVYeZYctMnwvvX79oU6rjwEfV+vaa/rNeLsuZ95SK2bi6xPMOVhe65MBEHU8o8dGOf3NLxmUY7i6RZB/f/HrgGebC0JLTHoW311hs+wLWmKN4b1BfRF3Y+1PmAA9vOhnWCeIjhqEcVNtdQy12A=
  true:
    tags: true
    condition: ${TRAVIS_PYTHON_VERSION} == 3.6
